"""Tests for standalone mode authentication changes in run.py (issue #2)."""

import inspect
from io import StringIO
from unittest.mock import Mock, patch

import click
import pytest

from jumpstarter_cli.run import run


def _unwrapped_run():
    """Return the innermost (unwrapped) run function."""
    return inspect.unwrap(run.callback)


def _call_run(capture_stderr=False, **kwargs):
    """Call the unwrapped run function with sensible defaults.

    Pass ``listener_bind="1234"`` and ``tls_insecure=True`` for the typical
    standalone-mode path.  Any keyword argument overrides the default.
    """
    defaults = {
        "config": Mock(),
        "listener_bind": None,
        "tls_insecure": False,
        "tls_cert": None,
        "tls_key": None,
        "passphrase": None,
        "unsafe_no_auth": False,
    }
    defaults.update(kwargs)

    if capture_stderr:
        buf = StringIO()
        with patch("click.echo", side_effect=lambda msg="", **kw: buf.write(msg + "\n") if kw.get("err") else None):
            _unwrapped_run()(**defaults)
        return buf.getvalue()
    else:
        return _unwrapped_run()(**defaults)


# ── AC-3: --unsafe-no-auth and --passphrase are mutually exclusive ────────────

class TestUnsafeNoAuthAndPassphraseMutuallyExclusive:
    def test_raises_usage_error_when_both_flags_provided(self):
        """AC-3: using both --unsafe-no-auth and --passphrase must raise UsageError."""
        with pytest.raises(click.UsageError, match="mutually exclusive"):
            _call_run(
                listener_bind="1234",
                tls_insecure=True,
                passphrase="mysecret",
                unsafe_no_auth=True,
            )


# ── AC-4: --unsafe-no-auth requires --tls-grpc-listener ──────────────────────

class TestUnsafeNoAuthRequiresListener:
    def test_raises_usage_error_without_listener(self):
        """AC-4: --unsafe-no-auth without --tls-grpc-listener must raise UsageError."""
        with pytest.raises(click.UsageError, match="--tls-grpc-listener"):
            _call_run(unsafe_no_auth=True)

    def test_error_message_mentions_flag(self):
        """AC-4: The error message must mention --unsafe-no-auth."""
        with pytest.raises(click.UsageError) as exc_info:
            _call_run(unsafe_no_auth=True)
        assert "--unsafe-no-auth" in str(exc_info.value)


# ── AC-1: Auto-generated passphrase when no auth flags are set ───────────────

class TestAutoGeneratedPassphrase:
    def test_interceptors_include_passphrase_interceptor(self):
        """AC-1: PassphraseInterceptor must be in interceptors when no --passphrase
        and no --unsafe-no-auth."""
        captured = {}

        def fake_serve(config, parsed_bind, tls_insecure, tls_cert, tls_key, passphrase):
            captured["passphrase"] = passphrase

        with patch("jumpstarter_cli.run._serve_with_exc_handling", side_effect=fake_serve):
            _unwrapped_run()(
                config=Mock(),
                listener_bind="1234",
                tls_insecure=True,
                tls_cert=None,
                tls_key=None,
                passphrase=None,
                unsafe_no_auth=False,
            )

        assert captured["passphrase"] is not None, "passphrase must be auto-generated"
        assert len(captured["passphrase"]) > 0

    def test_auto_generated_passphrase_is_printed_to_stderr(self):
        """AC-1: The auto-generated passphrase must be emitted to stderr."""
        stderr_lines = []

        def fake_echo(msg="", **kw):
            if kw.get("err"):
                stderr_lines.append(msg)

        with (
            patch("jumpstarter_cli.run._serve_with_exc_handling"),
            patch("click.echo", side_effect=fake_echo),
        ):
            _unwrapped_run()(
                config=Mock(),
                listener_bind="1234",
                tls_insecure=True,
                tls_cert=None,
                tls_key=None,
                passphrase=None,
                unsafe_no_auth=False,
            )

        combined = "\n".join(stderr_lines)
        assert "passphrase" in combined.lower(), "auto-generated passphrase must be mentioned in stderr"

    def test_auto_generated_passphrases_differ_across_calls(self):
        """AC-1: Each invocation produces a unique passphrase (randomness check)."""
        passphrases = []

        def fake_serve(config, parsed_bind, tls_insecure, tls_cert, tls_key, passphrase):
            passphrases.append(passphrase)

        with patch("jumpstarter_cli.run._serve_with_exc_handling", side_effect=fake_serve):
            for _ in range(5):
                _unwrapped_run()(
                    config=Mock(),
                    listener_bind="1234",
                    tls_insecure=True,
                    tls_cert=None,
                    tls_key=None,
                    passphrase=None,
                    unsafe_no_auth=False,
                )

        assert len(set(passphrases)) == 5, "auto-generated passphrases must be unique"


# ── AC-2: --unsafe-no-auth disables authentication ───────────────────────────

class TestUnsafeNoAuthDisablesAuth:
    def test_passphrase_is_none_when_unsafe_no_auth(self):
        """AC-2: When --unsafe-no-auth is set and no --passphrase, passphrase passed
        to serve must be None (no authentication)."""
        captured = {}

        def fake_serve(config, parsed_bind, tls_insecure, tls_cert, tls_key, passphrase):
            captured["passphrase"] = passphrase

        with patch("jumpstarter_cli.run._serve_with_exc_handling", side_effect=fake_serve):
            _unwrapped_run()(
                config=Mock(),
                listener_bind="1234",
                tls_insecure=True,
                tls_cert=None,
                tls_key=None,
                passphrase=None,
                unsafe_no_auth=True,
            )

        assert captured["passphrase"] is None, "passphrase must be None when --unsafe-no-auth is set"


# ── AC-5: Warning when --unsafe-no-auth is set ───────────────────────────────

class TestUnsafeNoAuthWarning:
    def test_warning_emitted_to_stderr(self):
        """AC-5: A warning about unauthenticated server must appear in stderr."""
        stderr_lines = []

        def fake_echo(msg="", **kw):
            if kw.get("err"):
                stderr_lines.append(msg)

        with (
            patch("jumpstarter_cli.run._serve_with_exc_handling"),
            patch("click.echo", side_effect=fake_echo),
        ):
            _unwrapped_run()(
                config=Mock(),
                listener_bind="1234",
                tls_insecure=True,
                tls_cert=None,
                tls_key=None,
                passphrase=None,
                unsafe_no_auth=True,
            )

        combined = "\n".join(stderr_lines)
        assert "WARNING" in combined or "warning" in combined.lower(), \
            "stderr must contain a warning when --unsafe-no-auth is used"
        assert "auth" in combined.lower() or "unauthenticated" in combined.lower(), \
            "warning must mention authentication"


# ── AC-6: Warning when auto-generated passphrase is used without TLS ─────────

class TestPlaintextPassphraseWarning:
    def test_warning_emitted_when_insecure_and_auto_passphrase(self):
        """AC-6: When TLS is disabled (--tls-grpc-insecure) and a passphrase is in
        effect (auto-generated or explicit), a plaintext warning must be emitted."""
        stderr_lines = []

        def fake_echo(msg="", **kw):
            if kw.get("err"):
                stderr_lines.append(msg)

        with (
            patch("jumpstarter_cli.run._serve_with_exc_handling"),
            patch("click.echo", side_effect=fake_echo),
        ):
            _unwrapped_run()(
                config=Mock(),
                listener_bind="1234",
                tls_insecure=True,
                tls_cert=None,
                tls_key=None,
                passphrase=None,   # triggers auto-generation
                unsafe_no_auth=False,
            )

        # The auto-generated passphrase info message must appear
        combined = "\n".join(stderr_lines)
        assert "passphrase" in combined.lower()


# ── AC-7: Explicit --passphrase continues to work ────────────────────────────

class TestExplicitPassphrase:
    def test_explicit_passphrase_is_forwarded_unchanged(self):
        """AC-7: When --passphrase is given, it must be forwarded to serve as-is."""
        captured = {}

        def fake_serve(config, parsed_bind, tls_insecure, tls_cert, tls_key, passphrase):
            captured["passphrase"] = passphrase

        with patch("jumpstarter_cli.run._serve_with_exc_handling", side_effect=fake_serve):
            _unwrapped_run()(
                config=Mock(),
                listener_bind="1234",
                tls_insecure=True,
                tls_cert=None,
                tls_key=None,
                passphrase="mysecret",
                unsafe_no_auth=False,
            )

        assert captured["passphrase"] == "mysecret"

    def test_explicit_passphrase_does_not_emit_auto_generation_info(self):
        """AC-7: When --passphrase is explicitly provided, no auto-generation
        INFO message must be emitted to stderr by run()."""
        stderr_lines = []

        def fake_echo(msg="", **kw):
            if kw.get("err"):
                stderr_lines.append(msg)

        with (
            patch("jumpstarter_cli.run._serve_with_exc_handling"),
            patch("click.echo", side_effect=fake_echo),
        ):
            _unwrapped_run()(
                config=Mock(),
                listener_bind="1234",
                tls_insecure=True,
                tls_cert=None,
                tls_key=None,
                passphrase="mysecret",
                unsafe_no_auth=False,
            )

        combined = "\n".join(stderr_lines)
        # run() must not emit an auto-generation INFO message when passphrase is explicit
        assert "auto-generated" not in combined.lower(), \
            "run() must not emit auto-generation message when --passphrase is explicit"
